[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "UniversalFunctions"
version = "2.1.1"
description = "A Python utility library providing foundational functions, validators, and infrastructure."
readme = "README.md"
requires-python = ">=3.14"

authors = [
    { name = "Miah M. Sabiq", email = "miah.sabiq@gibs.at"}
]

[tool.setuptools.packages.find]
include = [
    "UF*",
]